"""
Pydantic models for structured AI team output.
"""

from pydantic import BaseModel, Field


class FileEntry(BaseModel):
    """A single generated file."""
    path: str = Field(
        description="File path relative to project root, e.g. 'app/main.py' or 'Dockerfile'"
    )
    content: str = Field(
        description="Full file contents"
    )


class CodeOutput(BaseModel):
    """All files generated by a task."""
    files: list[FileEntry] = Field(
        description="List of all generated source files"
    )
