"""
Short code generation service.

Generates unique short codes using base62 encoding of a sequence number
with collision retry logic.
"""

import secrets
from typing import Optional

from app.config import settings
from app.utils.base62 import encode_base62


class CodeGenerator:
    """
    Generates unique short codes for URLs.

    Uses a combination of base62 encoding and random suffix for uniqueness.
    Implements retry logic for collision handling (max 3 attempts as per spec).
    """

    MAX_RETRIES = 3

    def __init__(self, code_length: Optional[int] = None):
        """
        Initialize the code generator.

        Args:
            code_length: Length of generated codes. Defaults to settings.short_code_length.
        """
        self.code_length = code_length or settings.short_code_length

    def generate(self, sequence_number: int) -> str:
        """
        Generate a short code from a sequence number.

        The code is generated by base62-encoding the sequence number and
        padding/truncating to the desired length. If the encoded value is
        shorter than required, random characters are appended.

        Args:
            sequence_number: A unique sequence number (e.g., from DB sequence).

        Returns:
            A short code string of length self.code_length.
        """
        # Encode the sequence number to base62
        encoded = encode_base62(sequence_number)

        # If encoded is shorter than desired length, pad with random chars
        if len(encoded) < self.code_length:
            padding_length = self.code_length - len(encoded)
            random_suffix = self._generate_random_suffix(padding_length)
            return encoded + random_suffix

        # If encoded is longer, truncate (shouldn't happen with proper sequence management)
        return encoded[: self.code_length]

    def generate_with_retry(
        self, sequence_number: int, is_code_taken: callable
    ) -> str:
        """
        Generate a short code with collision retry logic.

        Attempts to generate a unique code up to MAX_RETRIES times.
        On collision, modifies the sequence number and tries again.

        Args:
            sequence_number: Base sequence number.
            is_code_taken: Async callable that checks if a code already exists.

        Returns:
            A unique short code.

        Raises:
            RuntimeError: If unable to generate unique code after max retries.
        """
        import asyncio

        for attempt in range(self.MAX_RETRIES):
            # Add attempt offset to sequence for retry variation
            adjusted_sequence = sequence_number + (attempt * 1000)
            code = self.generate(adjusted_sequence)

            # Check if code is already taken
            if not is_code_taken(code):
                return code

        raise RuntimeError(
            f"Failed to generate unique short code after {self.MAX_RETRIES} attempts"
        )

    def _generate_random_suffix(self, length: int) -> str:
        """
        Generate a random base62 suffix of given length.

        Args:
            length: Number of random characters to generate.

        Returns:
            Random base62 string.
        """
        from app.utils.base62 import BASE62_ALPHABET

        return "".join(secrets.choice(BASE62_ALPHABET) for _ in range(length))